# Create squid directories
d /run/squid 0750 _squid _squid -
d /var/lib/squid 0750 _squid _squid -
d /var/log/squid 0750 _squid _squid -
d /var/spool/squid 0750 _squid _squid -
d /var/cache/squid 0750 _squid _squid -
