pkgname = "caddy-hazelesque"
pkgver = "2.10.0"
pkgrel = 0
build_style = "go"
# Build the custom main package (files/cmd/caddy-hazelesque/main.go)
# rather than upstream's cmd/caddy.  Our main.go imports the
# stock standard-modules plus a curated set of DNS-challenge
# providers baked in at link time.
make_build_args = ["./cmd/caddy-hazelesque"]
hostmakedepends = ["go"]
makedepends = ["dinit-chimera"]
# No runtime deps beyond what Go statically links.
pkgdesc = "Caddy web server with extra DNS-challenge modules baked in"
license = "Apache-2.0"
url = "https://github.com/caddyserver/caddy"
source = f"{url}/archive/refs/tags/v{pkgver}.tar.gz"
# PLACEHOLDER — operator runs `cbuild prepare-upgrade` (or hand-
# computes via `sha256sum caddy-2.10.0.tar.gz`) to fill in the
# real digest at the chosen version.
sha256 = "e07e2747c394a6549751950ec8f7457ed346496f131ee38538ae39cf89ebcc68"
# !check: upstream tests need a network + a writable Go cache,
#         neither of which the cbuild sandbox grants by default.
# !cross: haven't validated cross-arch Go builds for this template;
#         re-enable when we actually need an aarch64 caddy.
# !distlicense: license install handled explicitly in post_install.
options = ["!check", "!cross", "!distlicense"]


def post_extract(self):
    """
    Three steps, in order:

      1. Apply the go.mod/go.sum patches from `files/` so the
         module graph is fully pinned before any `go` tool runs.
      2. Generate cmd/caddy-hazelesque/main.go from the curated
         dns_modules list below.
      3. Populate the Go module cache via `go mod download`
         (needs network; offline thereafter).

    The patches MUST be applied here, not via cports' `patches/`
    dir — cports' patch phase runs AFTER prepare, by which time
    the `go` build-style has already auto-`go mod download`'d
    against pristine go.mod, and Go's import-resolution
    machinery has mutated go.mod (it auto-adds requires for any
    imports it finds in source files that aren't in go.mod yet).
    Doing patches → main.go → download in post_extract sidesteps
    that whole timing trap.

    The patches in `files/` are pre-resolved snapshots —
    generated locally via the workflow in
    REGENERATING-CADDY-PATCHES.md (one level up from cports/).
    They include:
      * `require` lines for each entry in dns_modules
      * `replace` directives pinning quic-go to v0.50.1 AND
        qpack to v0.5.1 (caddy 2.10's compiled-against pair —
        newer quic-go drops http3.QUICEarlyListener; newer
        qpack changes NewDecoder's signature, which v0.50.1's
        http3 package depends on; they're an API-coupled pair)
      * MVS-driven upgrades of other transitive deps the
        plugins demand (certmagic, libdns, etc.)

    If you edit dns_modules, you MUST regenerate the patches
    — go build will fail otherwise (declared requires won't
    match the blank imports).  See REGENERATING-CADDY-PATCHES.md
    (one level up from cports/).
    """
    # Step 1: apply the pinned go.mod / go.sum diffs.
    # `self.do` runs commands inside the bwrap sandbox, where
    # cports does NOT bind-mount the template's `files/` dir,
    # so we can't reference the patch via its host path.  Copy
    # into the build tree (which IS bind-mounted at /builddir/...)
    # first, apply with a cwd-relative path, then drop the copies.
    patches = (
        "add-dns-plugins-go.mod.patch",
        "add-dns-plugins-go.sum.patch",
    )
    for patch in patches:
        (self.cwd / patch).write_bytes((self.files_path / patch).read_bytes())
    for patch in patches:
        self.do("patch", "-p1", "-i", patch)
        (self.cwd / patch).unlink()
    # Curated DNS-challenge modules baked in at link time.
    # Edit this list AND regenerate the patches (see
    # REGENERATING-CADDY-PATCHES.md (one level up from cports/)) to add a provider not yet
    # listed.  xcaddy is explicitly NOT used — compile-it-
    # yourself is the Caddy story Chimera packages should
    # follow, not "fetch a binary generator".  Each entry is
    # a Go module path; the matching blank import lands in
    # main.go via the loop below.
    dns_modules = [
        "github.com/caddy-dns/linode",
        "github.com/caddy-dns/dnsimple",
        "github.com/caddy-dns/powerdns",
        "github.com/caddy-dns/rfc2136",
        # Add e.g. "github.com/caddy-dns/hetzner" here.
    ]

    main_dir = self.cwd / "cmd" / "caddy-hazelesque"
    main_dir.mkdir(parents=True, exist_ok=True)

    blank_imports = "\n".join(f'\t_ "{m}"' for m in dns_modules)
    main_src = f"""package main

// caddy-hazelesque — Hazel's flavour of Caddy with extra
// DNS-challenge modules baked in.  Generated by
// hazelesque/caddy-hazelesque template's post_extract; do not
// edit by hand inside the build tree.

import (
\tcaddycmd "github.com/caddyserver/caddy/v2/cmd"

\t// Standard Caddy modules (HTTP server, file_server,
\t// reverse_proxy, ACME issuers, etc.)
\t_ "github.com/caddyserver/caddy/v2/modules/standard"

\t// DNS-challenge providers — list curated in
\t// `dns_modules` in the cports template.
{blank_imports}
)

func main() {{
\tcaddycmd.Main()
}}
"""
    (main_dir / "main.go").write_text(main_src)

    # Populate the Go module cache from the patched
    # go.mod/go.sum.  `-mod=readonly` is the safety belt:
    # if anything in the patched state were inconsistent
    # (missing sum, version drift), `download` would fail
    # loudly rather than silently mutating go.mod.  Needs
    # network because cports' module cache may be cold;
    # passed explicitly because `self.do` defaults to
    # network-off even in the extract phase.  Subsequent
    # builds hit cbuild_cache/golang/pkg/mod/ and run offline.
    self.do(
        "go",
        "mod",
        "download",
        env={"GOFLAGS": "-mod=readonly"},
        allow_network=True,
    )


def post_install(self):
    self.install_license("LICENSE")
    self.install_file(self.files_path / "Caddyfile.example", "etc/caddy")
    self.install_sysusers(self.files_path / "sysusers.conf", name="caddy")
    self.install_tmpfiles(self.files_path / "tmpfiles.conf", name="caddy")
    self.install_service(self.files_path / "caddy")
