# SCIP indexer for Java, Scala, and Kotlin.  Source-built via the
# in-tree `./sbt` -> `./bin/coursier launch sbt` -> sbt 1.11 ->
# scalac chain that scip-java upstream ships.  Result is an
# sbt-pack tree (launcher + jars) under scip-java/target/pack/;
# we install the lib/ jars under /usr/share/scip-java/ and the
# generated launcher at /usr/bin/scip-java.
#
# About the build infrastructure scip-java ships in-tree:
#
#   - bin/coursier (159 KB) — a self-contained sh+ZIP launcher
#     for Coursier (Java bytecode in a JAR with a shell stub).
#     Pure JVM bytecode, runs anywhere a JDK does.  This is build
#     infrastructure that came with the upstream tarball, same
#     status as any project's checked-in bootstrap script (cf.
#     bazel's compile.sh, gradle's gradle-wrapper.jar) — not a
#     binary blob we are slapping on.
#
#   - ./sbt — three-line script that does
#     `./bin/coursier launch --jvm 11 sbt`.  Patched here to drop
#     `--jvm 11` (Coursier would try to download JDK 11 from
#     cdn.azul.com; we have no JDK 11 locally and the sandbox
#     blocks that download anyway).  sbt 1.11 runs fine on JDK 21.
#
# Network is required during prepare() because Coursier resolves
# ~hundreds of Maven artifacts from Maven Central at build time
# (scalameta, scala-xml, kotlin-compiler-embeddable, etc.).  Same
# pattern as bazel-7.4.0-bootstrap, with the same TODO to vendor
# the maven cache into source = [...] entries for sealed offline
# builds.

pkgname = "scip-java"
pkgver = "0.12.3"
pkgrel = 0
archs = ["aarch64", "ppc64le", "x86_64"]
prepare_after_patch = True
hostmakedepends = [
    "bash",
    "openjdk21",
    # System protoc for sbt-protoc — upstream pins protoc 3.17.3
    # via `PB.protocVersion`, which makes protocbridge fetch a
    # `protoc-linux-x86_64-3.17.3` from Maven that's glibc-linked
    # and won't exec on musl.  The ChimeraProtocOverride autoplugin
    # patched into project/ redirects PB.protocExecutable at the
    # system /usr/bin/protoc (5.32.x in cports today).  Wire
    # format and basic Java codegen are compatible across protoc
    # versions for the proto3 syntax scip-java uses.  protobuf-
    # protoc is the subpackage that ships /usr/bin/protoc; the
    # `protobuf` package itself is just the runtime libraries.
    "protobuf-protoc",
]
makedepends = [
    "openjdk21-jdk",
]
depends = [
    "java-jre-headless-openjdk21-default",
]
pkgdesc = "SCIP indexer for Java, Scala, and Kotlin"
license = "Apache-2.0"
url = "https://github.com/sourcegraph/scip-java"
source = f"{url}/archive/refs/tags/v{pkgver}.tar.gz"
sha256 = "7dbc2eb78541cec49540daefa8e4892110a1e2f680afb1d187874e8fd044b585"
# `sbt test` runs the upstream Scala test suite which fetches
# additional artifacts and snapshots.  Skip during package build;
# upstream CI is the place for that.
options = [
    "!check",
    "!cross",
    "!debug",
    "!distlicense",
    "!lto",
    "!parallel",
    "!scanrundeps",
    "!strip",
    "foreignelf",
]


def init_prepare(self):
    self.env["JAVA_HOME"] = "/usr/lib/jvm/java-21-openjdk"
    # Coursier defaults its cache to $HOME/.cache/coursier, which
    # lands in /tmp inside cports' bwrap (tmpfs, wiped between
    # phases).  Redirect to /builddir for persistence — same
    # pattern as bazel-7.4.0's --output_user_root.
    self.env["COURSIER_CACHE"] = "/builddir/.coursier-cache"
    # sbt also has its own caches.  Point them at /builddir too
    # so warm rebuilds are actually warm.
    self.env["SBT_OPTS"] = (
        "-Dsbt.global.base=/builddir/.sbt "
        "-Dsbt.boot.directory=/builddir/.sbt/boot "
        "-Dsbt.ivy.home=/builddir/.ivy2"
    )


def prepare(self):
    self.do(
        "./sbt",
        "cli/pack",
        env=self.env,
        allow_network=True,
    )


def build(self):
    pass


def install(self):
    self.install_license("LICENSE")
    # sbt-pack drops a runnable tree under scip-java/target/pack/
    # with bin/<launcher> and lib/<jar...>.  The launcher is
    # generated by sbt-pack with a relocation-safe PROG_HOME based
    # on `dirname $(readlink -f $0)`, so installing the whole tree
    # under /usr/share/scip-java and symlinking the launcher into
    # /usr/bin works without further patching.
    self.install_files("scip-java/target/pack/bin", "usr/share/scip-java")
    self.install_files("scip-java/target/pack/lib", "usr/share/scip-java")
    self.install_dir("usr/bin")
    self.install_link("usr/bin/scip-java", "../share/scip-java/bin/scip-java")
